---
version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily
  groups:
    patch:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "patch"

- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  groups:
    patch:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "patch"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  groups:
    patch:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "patch"

- package-ecosystem: npm
  directory: /frontend/
  ignore:
  - dependency-name: '*'
    update-types: [version-update:semver-major]
  schedule:
    interval: daily
  groups:
    patch:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "patch"

- package-ecosystem: gitsubmodule
  directory: /
  schedule:
    interval: daily
